ENV_ID = "CartPole-v1"
TOTAL_TIMESTEPS = 2500
TOTAL_TIMESTEPS = 150000
# TOTAL_TIMESTEPS = 250000
SEED = 0

ALGORITHM = "PPO"
# ALGORITHM = "DQN"
POLICY = "MlpPolicy"

USE_CUSTOM_ENV = True
DO_LEARNING = True
DO_EVALUATION = True
